import Vue from 'vue'
import colors from 'vuetify/lib/util/colors'
import Vuetify from 'vuetify/lib'
import { Touch } from 'vuetify/lib/directives'
import en from 'vuetify/lib/locale/en'
// import '@fortawesome/fontawesome-free/css/all.css'

Vue.use(Vuetify, {
  directives: {
    Touch,
  },
})

export default new Vuetify({
  lang: {
    locales: { en },
    current: 'en',
    defaultLocale: 'en',
  },
  theme: {
    themes: {
      light: {
        primary: '#990200',
        secondary: '#004777',
        accent: '#990200',
        ...colors
      }
    },
    options: {
      customProperties: true
    },
  },
  icons: {
    iconfont: 'fa',
    values: {
      // generales
      account: 'fas fa-user-circle',
      add: 'fas fa-plus',
      attach: 'fas fa-paperclip',
      calendar: 'fas fa-calendar-alt',
      camera: 'fas fa-camera',
      cameraFlip: 'fas fa-sync',
      caretDown: 'fas fa-caret-down',
      caretLeft: 'fas fa-caret-left',
      caretRight: 'fas fa-caret-right',
      caretUp: 'fas fa-caret-up',
      chat: 'fas fa-comment',
      check: 'fas fa-check',
      checkAll: 'fas fa-check-double',
      database: 'fas fa-database',
      debug: 'fas fa-bug',
      delete: 'fas fa-times',
      down: 'fas fa-chevron-down',
      download: 'fas fa-cloud-download-alt',
      edit: 'fas fa-edit',
      email: 'fas fa-envelope',
      equals: 'fas fa-equals',
      erase: 'fas fa-eraser',
      exclamation: 'fas fa-exclamation',
      export: 'fas fa-file-export',
      filter: 'fas fa-filter',
      import: 'fas fa-download',
      info: 'fas fa-info-circle',
      hide: 'fas fa-eye-slash',
      locked: 'fas fa-lock',
      map: 'fas fa-map',
      mapLocation: 'fas fa-map-marker',
      minus: 'fas fa-minus',
      more: 'fas fa-ellipsis-v',
      offline: 'signal_cellular_off',
      phone: 'fas fa-phone',
      purge: 'fas fa-toilet',
      refresh: 'fas fa-sync',
      route: 'fas fa-route',
      search: 'fas fa-search',
      select: 'fas fa-object-group',
      show: 'fas fa-eye',
      shutter: 'fas fa-circle',
      send: 'fas fa-paper-plane',
      signature: 'fas fa-signature',
      sort: 'fas fa-sort-alpha-up',
      sync: 'fas fa-cloud-upload-alt',
      thumbsDown: 'fas fa-thumbs-down',
      thumbsUp: 'fas fa-thumbs-up',
      undo: 'fas fa-undo',
      unlocked: 'fas fa-unlock',
      up: 'fas fa-chevron-up',
      upload: 'fas fa-upload',
      user: 'fas fa-user',
      warning: 'fas fa-exclamation-triangle',
      home: 'fas fa-home',
      mark: 'fas fa-check-circle',
      unmark: 'fas fa-circle',
      // dominio
      almacen: 'fas fa-box-open',
      accionCorrectora: 'fas fa-band-aid',
      accionMaterial: 'fas fa-tools',
      anomaliaChecklist: 'fas fa-exclamation',
      articulo: 'fas fa-hdd',
      asignado: 'fas fa-hand-point-right',
      avisarAntesDeIr: 'fas fa-phone',
      bajaDefinitiva: 'fas fa-thumbs-down',
      checklist: 'fas fa-tasks',
      cliente: 'fas fa-user',
      clienteCuenta: 'fas fa-university',
      cobrar: 'fas fa-euro-sign',
      conFechaFijada: 'fas fa-clock',
      contratos: 'fa-solid fa-file-contract',
      cronometro: 'fas fa-stopwatch',
      cronometroDetener: 'fas fa-stopwatch-20',
      cuadrante: 'fas fa-border-all',
      cuotas: 'fas fa-tasks',
      datoPersonalizado: 'fas fa-database',
      descargarVehiculo: 'fas fa-dolly',
      desplazamiento: 'fas fa-shipping-fast',
      devolucionMaterial: 'fas fa-shipping-fast',
      direcciones: 'fas fa-map-marker',
      documentacionEnviar: 'fas fa-file-alt',
      entrada: 'fas fa-sign-in-alt',
      escandallo: 'fas fa-sitemap',
      estudioFinanciero: 'fas fa-hand-holding-usd',
      facturacion: 'fas fa-money-bill',
      facturas: 'fa-solid fa-file-invoice',
      fichaTecnica: 'fas fa-book-open',
      finalizar: 'fas fa-flag-checkered',
      idioma: 'fas fa-solid fa-language',
      lpresupuestocli: 'fas fa-layer-group',
      llavero: 'fas fa-key',
      manoDeObra: 'fas fa-user-clock',
      materialAfectado: 'fas fa-cubes',
      materialInstalar: 'fas fa-layer-group',
      motivoBloqueo: 'fas fa-lock',
      nfc: 'fas fa-tag',
      novedad: 'fas fa-bell',
      orden: 'fas fa-clipboard-list',
      parte: 'fas fa-clipboard',
      personaContacto: 'fas fa-users',
      preguntaChecklist: 'fas fa-question',
      preguntaChecklistValores: 'fas fa-pencil-ruler',
      preguntaChecklistOk: 'fas fa-thumbs-up',
      preguntaChecklistMal: 'fas fa-thumbs-down',
      preguntaChecklistNoProcede: 'fas fa-ban',
      preguntaChecklistDesconocido: 'fas fa-question-circle',
      presencia: 'fas fa-hourglass',
      presenciaConSalida: 'fas fa-check',
      presenciaSinSalida: 'fas fa-exclamation',
      presupuestos: 'fas fa-euro-sign',
      presurizacion: 'fas fa-compress-arrows-alt',
      prioridad: 'fas fa-sort-numeric-up',
      puntoControl: 'fas fa-dot-circle',
      qr: 'fas fa-qrcode',
      recarga: 'fas fa-charging-station',
      representantes: 'fa-solid fa-user-tie',
      retimbrado: 'fas fa-stamp',
      revision: 'fas fa-clipboard-check',
      retiradaTemporal: 'fas fa-people-carry',
      ronda: 'fas fa-wave-square',
      salida: 'fas fa-sign-out-alt',
      servicioVigilancia: 'fas fa-eye',
      servicioContratado: 'fas fa-hand-holding-usd',
      sistema: 'fas fa-building',
      sobre: 'fas fa-envelope',
      subsistema: 'fas fa-server',
      sustitucion: 'fas fa-exchange-alt',
      tiempoTrabajado: 'fas fa-business-time',
      tipoActuacion: 'fas fa-tag',
      turno: 'fas fa-calendar-alt',
      ubicacion: 'fas fa-crosshairs',
      vehiculo: 'fas fa-truck',
      viaComunicacion: 'fas fa-broadcast-tower',
      vigilante: 'fas fa-user-shield',
    }
  },
})
